# Generated by Django 3.2.7 on 2021-09-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210930_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doner',
            name='phno',
            field=models.CharField(max_length=15),
        ),
    ]
